#!/usr/bin/env python3
"""Inline every asset into one portable HTML file: tamriel-mapchart.html"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def read(rel):
    with open(os.path.join(ROOT, rel), encoding='utf-8') as f:
        return f.read()


html = read('index.html')

# stylesheet -> <style>
html = re.sub(
    r'<link rel="stylesheet" href="css/app\.css">',
    lambda m: '<style>\n' + read('css/app.css') + '\n</style>',
    html)

# scripts -> inline, in the original order
def inline_script(m):
    src = m.group(1)
    return '<script>\n/* ---- ' + src + ' ---- */\n' + read(src) + '\n</script>'


html = re.sub(r'<script src="([^"]+)"></script>', inline_script, html)

banner = ('<!-- Tamriel MapChart -- single-file build.\n'
          '     Generated by tools/bundle.py; edit the sources, not this file. -->\n')
out = os.path.join(ROOT, 'tamriel-mapchart.html')
with open(out, 'w', encoding='utf-8') as f:
    f.write(banner + html)

assert 'src="js/' not in html and 'href="css/' not in html, 'an asset was left external'
print('wrote %s (%.0f KB)' % (out, os.path.getsize(out) / 1024.0))
